### ISSUE TITLE
Wondering if.. :)

### ISSUE THREAD

**Issue by EniGmqTiK** [jason0611/FS22_RealisticPlayerSize#4]
Hi,

Thank you for the mod first !
Nice idea, as I play using a head tracker, it helps a lot !

Looking at the files I was wondering if there was an issue or I missed understood the code (that could be it for sure!).
About the lines 23 and 25 in realisticPlayerSize.lua where you put "1.68" , maybe you meant 1.86 ?  

Cheers !

**Comment by jason0611** [comment]
Hi,
the similarity of the numbers is random. 1.68 is the normalization factor, 1.86m is the size I found most suitable for me. :-)
